-- ============================================================
-- GAIA TOURS & TRAVEL — Multilingual Completion (EN/AR)
-- Migration #7
-- ------------------------------------------------------------
-- Adds ALL remaining EN/AR translation keys for the Tours
-- module (weroad/search.php, trip.php, booking.php) so that no
-- user-facing text remains hardcoded in templates.
-- Safe to run repeatedly (idempotent).
-- ============================================================

-- ============ TOURS SEARCH PAGE ============
INSERT IGNORE INTO translations (`key`, lang, `value`, `group`) VALUES
('tours.search_where',        'en', 'Where', 'tours'),
('tours.search_where',        'ar', 'أين', 'tours'),
('tours.search_when',         'en', 'When', 'tours'),
('tours.search_when',         'ar', 'متى', 'tours'),
('tours.search_dest_ph',      'en', 'Search destination', 'tours'),
('tours.search_dest_ph',      'ar', 'ابحث عن وجهة', 'tours'),
('tours.search_btn',          'en', 'Search', 'tours'),
('tours.search_btn',          'ar', 'بحث', 'tours'),
('tours.search_view_by',      'en', 'View by', 'tours'),
('tours.search_view_by',      'ar', 'عرض حسب', 'tours'),
('tours.search_trips_tab',    'en', 'Trips', 'tours'),
('tours.search_trips_tab',    'ar', 'الجولات', 'tours'),
('tours.search_dates_tab',    'en', 'Dates', 'tours'),
('tours.search_dates_tab',    'ar', 'التواريخ', 'tours'),
('tours.search_show_maps',    'en', 'Show maps', 'tours'),
('tours.search_show_maps',    'ar', 'إظهار الخرائط', 'tours'),
('tours.search_found',        'en', '{count} trip(s) found', 'tours'),
('tours.search_found',        'ar', 'تم العثور على {count} رحلة', 'tours'),
('tours.search_no_results',   'en', 'No trips match your filters. Try adjusting your search.', 'tours'),
('tours.search_no_results',   'ar', 'لا توجد جولات تطابق عوامل التصفية. جرّب تعديل بحثك.', 'tours'),
('tours.search_compare',      'en', 'Compare', 'tours'),
('tours.search_compare',      'ar', 'مقارنة', 'tours'),
('tours.search_from',         'en', 'From', 'tours'),
('tours.search_from',         'ar', 'من', 'tours'),
('tours.search_days',         'en', '{days} days', 'tours'),
('tours.search_days',         'ar', '{days} أيام', 'tours'),
('tours.search_see_dates',    'en', 'See departure dates', 'tours'),
('tours.search_see_dates',    'ar', 'عرض مواعيد المغادرة', 'tours'),
('tours.search_show',         'en', 'Show {count}', 'tours'),
('tours.search_show',         'ar', 'عرض {count}', 'tours'),
('tours.search_page',         'en', 'Page {current} of {total}', 'tours'),
('tours.search_page',         'ar', 'صفحة {current} من {total}', 'tours'),
('tours.search_prev',         'en', 'Previous', 'tours'),
('tours.search_prev',         'ar', 'السابق', 'tours'),
('tours.search_next',         'en', 'Next', 'tours'),
('tours.search_next',         'ar', 'التالي', 'tours');

-- ============ TOURS TRIP DETAIL PAGE ============
INSERT IGNORE INTO translations (`key`, lang, `value`, `group`) VALUES
('tours.trip_reviews',        'en', '{count} reviews', 'tours'),
('tours.trip_reviews',        'ar', '{count} تقييم', 'tours'),
('tours.trip_days',           'en', '{days} days', 'tours'),
('tours.trip_days',           'ar', '{days} أيام', 'tours'),
('tours.trip_max_people',     'en', 'Max {count} people', 'tours'),
('tours.trip_max_people',     'ar', 'الحد الأقصى {count} أشخاص', 'tours'),
('tours.trip_effort',         'en', '{level} effort', 'tours'),
('tours.trip_effort',         'ar', 'جهد {level}', 'tours'),
('tours.trip_is_for_me',      'en', 'Is this trip for me?', 'tours'),
('tours.trip_is_for_me',      'ar', 'هل هذه الرحلة مناسبة لي؟', 'tours'),
('tours.trip_age_range',      'en', 'Age range', 'tours'),
('tours.trip_age_range',      'ar', 'الفئة العمرية', 'tours'),
('tours.trip_physical_effort','en', 'Physical effort', 'tours'),
('tours.trip_physical_effort','ar', 'الجهد البدني', 'tours'),
('tours.trip_comfort',        'en', 'Comfort level', 'tours'),
('tours.trip_comfort',        'ar', 'مستوى الراحة', 'tours'),
('tours.trip_accommodation',  'en', 'Accommodation', 'tours'),
('tours.trip_accommodation',  'ar', 'الإقامة', 'tours'),
('tours.trip_itinerary',      'en', 'Itinerary', 'tours'),
('tours.trip_itinerary',      'ar', 'برنامج الرحلة', 'tours'),
('tours.trip_day',            'en', 'Day {day}', 'tours'),
('tours.trip_day',            'ar', 'اليوم {day}', 'tours'),
('tours.trip_included_title', 'en', 'What''s included', 'tours'),
('tours.trip_included_title', 'ar', 'ماذا يشمل', 'tours'),
('tours.trip_included',       'en', 'Included', 'tours'),
('tours.trip_included',       'ar', 'مشمول', 'tours'),
('tours.trip_not_included',   'en', 'Not included', 'tours'),
('tours.trip_not_included',   'ar', 'غير مشمول', 'tours'),
('tours.trip_optional',       'en', 'Optional activities', 'tours'),
('tours.trip_optional',       'ar', 'أنشطة اختيارية', 'tours'),
('tours.trip_optional_sub',   'en', 'Bookable directly with your Group Leader during the trip.', 'tours'),
('tours.trip_optional_sub',   'ar', 'يمكن حجزها مباشرة مع قائد المجموعة أثناء الرحلة.', 'tours'),
('tours.trip_why',            'en', 'Why GAIA Tours', 'tours'),
('tours.trip_why',            'ar', 'لماذا غايا جولات', 'tours'),
('tours.trip_confidence',     'en', 'Book with confidence', 'tours'),
('tours.trip_confidence',     'ar', 'احجز بثقة', 'tours'),
('tours.trip_confidence_sub', 'en', 'Free cancellation up to 30 days before', 'tours'),
('tours.trip_confidence_sub', 'ar', 'إلغاء مجاني حتى 30 يومًا قبل الرحلة', 'tours'),
('tours.trip_small_groups',   'en', 'Small group sizes', 'tours'),
('tours.trip_small_groups',   'ar', 'مجموعات صغيرة', 'tours'),
('tours.trip_small_groups_sub','en', 'Max 20 travellers, always with a leader', 'tours'),
('tours.trip_small_groups_sub','ar', 'بحد أقصى 20 مسافرًا، دائمًا مع قائد', 'tours'),
('tours.trip_faq_title',      'en', 'FAQs — Frequently Asked Questions', 'tours'),
('tours.trip_faq_title',      'ar', 'الأسئلة الشائعة', 'tours'),
('tours.trip_from',           'en', 'From', 'tours'),
('tours.trip_from',           'ar', 'من', 'tours'),
('tours.trip_see_dates',      'en', 'See dates', 'tours'),
('tours.trip_see_dates',      'ar', 'عرض التواريخ', 'tours'),
('tours.trip_spots_left',     'en', 'Only {count} spots left for {month}', 'tours'),
('tours.trip_spots_left',     'ar', 'تبقى {count} أماكن فقط لشهر {month}', 'tours'),
('tours.trip_departures',     'en', '{count} departure date(s) available', 'tours'),
('tours.trip_departures',     'ar', 'تتوفر {count} موعد مغادرة', 'tours'),
('tours.trip_no_departures',  'en', 'No upcoming departures.', 'tours'),
('tours.trip_no_departures',  'ar', 'لا توجد مغادرات قادمة.', 'tours'),
('tours.trip_travellers',     'en', 'Over {count} GAIA travellers have done this trip', 'tours'),
('tours.trip_travellers',     'ar', 'أكثر من {count} مسافر من غايا قاموا بهذه الرحلة', 'tours'),
('tours.trip_installments',   'en', 'Interest-free installments', 'tours'),
('tours.trip_installments',   'ar', 'أقساط بدون فوائد', 'tours'),
('tours.trip_insurance',      'en', 'Medical & baggage insurance included', 'tours'),
('tours.trip_insurance',      'ar', 'التأمين الطبي وتأمين الأمتعة مشمول', 'tours'),
('tours.trip_ask',            'en', 'Ask an expert', 'tours'),
('tours.trip_ask',            'ar', 'اسأل خبيرًا', 'tours'),
('tours.trip_optional_price', 'en', 'Approx. ${price} per person.', 'tours'),
('tours.trip_optional_price', 'ar', 'تقريبًا ${price} لكل شخص.', 'tours');

-- ============ TOURS BOOKING PAGE ============
INSERT IGNORE INTO translations (`key`, lang, `value`, `group`) VALUES
('tours.booking_step1',       'en', 'Booking', 'tours'),
('tours.booking_step1',       'ar', 'الحجز', 'tours'),
('tours.booking_step2',       'en', 'Travellers details', 'tours'),
('tours.booking_step2',       'ar', 'تفاصيل المسافرين', 'tours'),
('tours.booking_step3',       'en', 'Account data', 'tours'),
('tours.booking_step3',       'ar', 'بيانات الحساب', 'tours'),
('tours.booking_step4',       'en', 'Payment', 'tours'),
('tours.booking_step4',       'ar', 'الدفع', 'tours'),
('tours.booking_mandatory',   'en', 'Mandatory fields *', 'tours'),
('tours.booking_mandatory',   'ar', 'حقول إلزامية *', 'tours'),
('tours.booking_fullname',    'en', 'Full name *', 'tours'),
('tours.booking_fullname',    'ar', 'الاسم الكامل *', 'tours'),
('tours.booking_email',       'en', 'Email *', 'tours'),
('tours.booking_email',       'ar', 'البريد الإلكتروني *', 'tours'),
('tours.booking_phone',       'en', 'Phone', 'tours'),
('tours.booking_phone',       'ar', 'الهاتف', 'tours'),
('tours.booking_who',         'en', 'Who are you booking for? *', 'tours'),
('tours.booking_who',         'ar', 'لمن تحجز؟ *', 'tours'),
('tours.booking_why_gender',  'en', 'Why we ask for your gender', 'tours'),
('tours.booking_why_gender',  'ar', 'لماذا نسأل عن جنسك', 'tours'),
('tours.booking_female',      'en', 'FEMALE', 'tours'),
('tours.booking_female',      'ar', 'أنثى', 'tours'),
('tours.booking_male',        'en', 'MALE', 'tours'),
('tours.booking_male',        'ar', 'ذكر', 'tours'),
('tours.booking_included_label','en', 'Included in your trip', 'tours'),
('tours.booking_included_label','ar', 'مشمول في رحلتك', 'tours'),
('tours.booking_included_sub',  'en', 'These options are already included in the price', 'tours'),
('tours.booking_included_sub',  'ar', 'هذه الخيارات مشمولة بالفعل في السعر', 'tours'),
('tours.booking_mixed_title', 'en', 'I''m OK with a mixed gender room', 'tours'),
('tours.booking_mixed_title', 'ar', 'أوافق على غرفة مختلطة', 'tours'),
('tours.booking_mixed_desc',  'en', 'In a mixed gender room, you might be sharing with other travellers of different genders, but don''t worry: you each get your own single bed. The "mixed" part just means fellow travellers from your group, not random strangers!', 'tours'),
('tours.booking_mixed_desc',  'ar', 'في غرفة مختلطة، قد تشارك مع مسافرين آخرين من جنس مختلف، لكن لا تقلق: لكل منكم سرير فردي خاص. المقصود بـ"مختلط" هو زملاؤك في المجموعة فقط، وليس غرباء!', 'tours'),
('tours.booking_insurance_title','en', 'Medical and Baggage Insurance included', 'tours'),
('tours.booking_insurance_title','ar', 'التأمين الطبي وتأمين الأمتعة مشمول', 'tours'),
('tours.booking_options_label','en', 'Options and extras', 'tours'),
('tours.booking_options_label','ar', 'الخيارات والإضافات', 'tours'),
('tours.booking_continue',    'en', 'Continue', 'tours'),
('tours.booking_continue',    'ar', 'متابعة', 'tours'),
('tours.booking_apply',       'en', 'Apply', 'tours'),
('tours.booking_apply',       'ar', 'تطبيق', 'tours'),
('tours.booking_promo_ph',    'en', 'e.g. WEROAD10', 'tours'),
('tours.booking_promo_ph',    'ar', 'مثال: WEROAD10', 'tours'),
('tours.booking_your_trip',   'en', 'Your trip', 'tours'),
('tours.booking_your_trip',   'ar', 'رحلتك', 'tours'),
('tours.booking_from',        'en', 'From', 'tours'),
('tours.booking_from',        'ar', 'من', 'tours'),
('tours.booking_to',          'en', 'To', 'tours'),
('tours.booking_to',          'ar', 'إلى', 'tours'),
('tours.booking_available',   'en', 'Available', 'tours'),
('tours.booking_available',   'ar', 'متاح', 'tours'),
('tours.booking_trip_price',  'en', 'Trip price', 'tours'),
('tours.booking_trip_price',  'ar', 'سعر الرحلة', 'tours'),
('tours.booking_flex_line',   'en', 'Flexible cancellation', 'tours'),
('tours.booking_flex_line',   'ar', 'الإلغاء المرن', 'tours'),
('tours.booking_room_line',   'en', 'Private room', 'tours'),
('tours.booking_room_line',   'ar', 'غرفة خاصة', 'tours'),
('tours.booking_discount',    'en', 'Discount', 'tours'),
('tours.booking_discount',    'ar', 'الخصم', 'tours'),
('tours.booking_total',       'en', 'Total', 'tours'),
('tours.booking_total',       'ar', 'الإجمالي', 'tours'),
('tours.booking_installments','en', 'Interest-free installments', 'tours'),
('tours.booking_installments','ar', 'أقساط بدون فوائد', 'tours'),
('tours.booking_social_proof','en', 'Over {count} GAIA travellers have already done this trip', 'tours'),
('tours.booking_social_proof','ar', 'أكثر من {count} مسافر من غايا قاموا بهذه الرحلة', 'tours'),
('tours.booking_need_help',   'en', 'Do you need help?', 'tours'),
('tours.booking_need_help',   'ar', 'هل تحتاج إلى مساعدة؟', 'tours');

-- ============ TOURS PROMO / NOT-FOUND MESSAGES ============
INSERT IGNORE INTO translations (`key`, lang, `value`, `group`) VALUES
('tours.promo_enter',         'en', 'Enter a promo code.', 'tours'),
('tours.promo_enter',         'ar', 'أدخل رمز الخصم.', 'tours'),
('tours.promo_applied',       'en', 'Promo applied! -€{amount}', 'tours'),
('tours.promo_applied',       'ar', 'تم تطبيق الرمز! -{amount} €', 'tours'),
('tours.promo_validate_error','en', 'Could not validate promo.', 'tours'),
('tours.promo_validate_error','ar', 'تعذر التحقق من الرمز.', 'tours'),
('tours.not_found_title',     'en', 'Trip not found', 'tours'),
('tours.not_found_title',     'ar', 'الجولة غير موجودة', 'tours'),
('tours.not_found_text',      'en', 'The trip you are looking for does not exist.', 'tours'),
('tours.not_found_text',      'ar', 'الجولة التي تبحث عنها غير موجودة.', 'tours'),
('tours.browse_trips',        'en', 'Browse trips', 'tours'),
('tours.browse_trips',        'ar', 'تصفح الجولات', 'tours');
