-- ============================================================
-- GAIA TOURS & TRAVEL — Unified Booking & Payment Architecture
-- Migration #11
-- ------------------------------------------------------------
-- Objective: Create a single booking architecture that supports
--   * Tours   (GAIA-TO-XXXXXX)
--   * Hotels  (GAIA-HO-XXXXXX)
--   * Rooms   (GAIA-RO-XXXXXX)
--   * Events  (GAIA-EV-XXXXXX)
--   * Transfers (GAIA-TR-XXXXXX)
-- and will later connect to CyberSource WITHOUT requiring a
-- database redesign.
--
-- Implements:
--   * booking_reference column + unique index on EVERY booking table
--     (GAIA-* format, unique, auto-generated by BookingReferenceService)
--   * Expanded booking status ENUM on every booking table:
--       pending, awaiting_payment, paid, confirmed, completed,
--       cancelled, refunded
--   * payments table upgraded (booking_reference, payment_method,
--     gateway_response JSON, authorization_code, payment_token,
--     expanded status ENUM)
--   * payment_transactions table (gateway abstraction + webhooks)
--   * invoices table (generic, reusable for all booking types)
--   * booking_logs table (audit timeline)
--   * room_bookings table (Room booking type)
--   * user_id NOT NULL enforcement on all booking tables
--
-- NO CyberSource API integration. NO real payment processing.
-- Database + architecture preparation only.
--
-- Safe to run repeatedly (idempotent).
-- ============================================================
USE gaia_tours;

-- ============================================================
-- 1) BOOKING REFERENCE MAPPING
--    Central helper used to backfill + validate references.
-- ============================================================
-- Per-type prefix mapping is handled in BookingReferenceService.php.
-- Here we only add columns/indexes.

-- ------------------------------------------------------------
-- 1a) bookings (transfers) — GAIA-TR-XXXXXX
-- ------------------------------------------------------------
SET @c := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='bookings' AND COLUMN_NAME='booking_reference');
SET @s := IF(@c=0, 'ALTER TABLE bookings ADD COLUMN booking_reference VARCHAR(30) NULL UNIQUE AFTER booking_code', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;

SET @i := (SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='bookings' AND INDEX_NAME='uq_bookings_ref');
SET @s := IF(@i=0, 'ALTER TABLE bookings ADD UNIQUE KEY uq_bookings_ref (booking_reference)', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;

-- Backfill existing rows with a reference (GAIA-TR- + zero-padded id)
UPDATE bookings SET booking_reference = CONCAT('GAIA-TR-', LPAD(id, 6, '0'))
WHERE booking_reference IS NULL OR booking_reference = '';

-- Expand status ENUM
SET @s := (SELECT IF(
  (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='bookings' AND COLUMN_NAME='status' AND COLUMN_TYPE LIKE '%refunded%') = 0,
  'ALTER TABLE bookings MODIFY COLUMN status ENUM(''pending'',''awaiting_payment'',''paid'',''confirmed'',''completed'',''cancelled'',''refunded'') NOT NULL DEFAULT ''pending''',
  'SELECT 1'));
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;

-- ------------------------------------------------------------
-- 1b) weroad_bookings (tours) — GAIA-TO-XXXXXX
-- ------------------------------------------------------------
SET @c := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='weroad_bookings' AND COLUMN_NAME='booking_reference');
SET @s := IF(@c=0, 'ALTER TABLE weroad_bookings ADD COLUMN booking_reference VARCHAR(30) NULL AFTER booking_code', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;

SET @i := (SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='weroad_bookings' AND INDEX_NAME='uq_wb_ref');
SET @s := IF(@i=0, 'ALTER TABLE weroad_bookings ADD UNIQUE KEY uq_wb_ref (booking_reference)', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;

UPDATE weroad_bookings SET booking_reference = CONCAT('GAIA-TO-', LPAD(id, 6, '0'))
WHERE booking_reference IS NULL OR booking_reference = '';

SET @s := (SELECT IF(
  (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='weroad_bookings' AND COLUMN_NAME='status' AND COLUMN_TYPE LIKE '%refunded%') = 0,
  'ALTER TABLE weroad_bookings MODIFY COLUMN status ENUM(''pending'',''awaiting_payment'',''paid'',''confirmed'',''completed'',''cancelled'',''refunded'') NOT NULL DEFAULT ''pending''',
  'SELECT 1'));
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;

-- ------------------------------------------------------------
-- 1c) hotel_bookings (hotels) — GAIA-HO-XXXXXX
-- ------------------------------------------------------------
SET @c := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='hotel_bookings' AND COLUMN_NAME='booking_reference');
SET @s := IF(@c=0, 'ALTER TABLE hotel_bookings ADD COLUMN booking_reference VARCHAR(30) NULL AFTER booking_code', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;

SET @i := (SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='hotel_bookings' AND INDEX_NAME='uq_hb_ref');
SET @s := IF(@i=0, 'ALTER TABLE hotel_bookings ADD UNIQUE KEY uq_hb_ref (booking_reference)', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;

UPDATE hotel_bookings SET booking_reference = CONCAT('GAIA-HO-', LPAD(id, 6, '0'))
WHERE booking_reference IS NULL OR booking_reference = '';

SET @s := (SELECT IF(
  (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='hotel_bookings' AND COLUMN_NAME='status' AND COLUMN_TYPE LIKE '%refunded%') = 0,
  'ALTER TABLE hotel_bookings MODIFY COLUMN status ENUM(''pending'',''awaiting_payment'',''paid'',''confirmed'',''completed'',''cancelled'',''refunded'') NOT NULL DEFAULT ''pending''',
  'SELECT 1'));
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;

-- ------------------------------------------------------------
-- 1d) event_bookings (events) — GAIA-EV-XXXXXX
-- ------------------------------------------------------------
SET @c := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='event_bookings' AND COLUMN_NAME='booking_reference');
SET @s := IF(@c=0, 'ALTER TABLE event_bookings ADD COLUMN booking_reference VARCHAR(30) NULL AFTER booking_code', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;

SET @i := (SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='event_bookings' AND INDEX_NAME='uq_eb_ref');
SET @s := IF(@i=0, 'ALTER TABLE event_bookings ADD UNIQUE KEY uq_eb_ref (booking_reference)', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;

UPDATE event_bookings SET booking_reference = CONCAT('GAIA-EV-', LPAD(id, 6, '0'))
WHERE booking_reference IS NULL OR booking_reference = '';

SET @s := (SELECT IF(
  (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='event_bookings' AND COLUMN_NAME='status' AND COLUMN_TYPE LIKE '%refunded%') = 0,
  'ALTER TABLE event_bookings MODIFY COLUMN status ENUM(''pending'',''awaiting_payment'',''paid'',''confirmed'',''completed'',''cancelled'',''refunded'') NOT NULL DEFAULT ''pending''',
  'SELECT 1'));
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;

-- ------------------------------------------------------------
-- 1e) taxi_bookings (taxis) — GAIA-TR-XXXXXX (same family as transfer)
-- ------------------------------------------------------------
SET @c := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='taxi_bookings' AND COLUMN_NAME='booking_reference');
SET @s := IF(@c=0, 'ALTER TABLE taxi_bookings ADD COLUMN booking_reference VARCHAR(30) NULL AFTER booking_code', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;

SET @i := (SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='taxi_bookings' AND INDEX_NAME='uq_tb_ref');
SET @s := IF(@i=0, 'ALTER TABLE taxi_bookings ADD UNIQUE KEY uq_tb_ref (booking_reference)', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;

UPDATE taxi_bookings SET booking_reference = CONCAT('GAIA-TR-', LPAD(id, 6, '0'))
WHERE booking_reference IS NULL OR booking_reference = '';

SET @s := (SELECT IF(
  (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='taxi_bookings' AND COLUMN_NAME='status' AND COLUMN_TYPE LIKE '%refunded%') = 0,
  'ALTER TABLE taxi_bookings MODIFY COLUMN status ENUM(''pending'',''awaiting_payment'',''paid'',''confirmed'',''completed'',''cancelled'',''refunded'') NOT NULL DEFAULT ''pending''',
  'SELECT 1'));
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;

-- ============================================================
-- 2) ROOM BOOKINGS (rooms) — GAIA-RO-XXXXXX
--    New table for the Room booking type.
-- ============================================================
CREATE TABLE IF NOT EXISTS room_bookings (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  booking_code VARCHAR(20) NOT NULL,
  booking_reference VARCHAR(30) NULL,
  hotel_id INT UNSIGNED NULL,
  room_id INT UNSIGNED NULL,
  user_id INT UNSIGNED NOT NULL,
  guest_name VARCHAR(150) NOT NULL,
  guest_email VARCHAR(150) NOT NULL,
  guest_phone VARCHAR(50) NULL,
  check_in_date DATE NOT NULL,
  check_out_date DATE NOT NULL,
  guests INT UNSIGNED NOT NULL DEFAULT 2,
  base_price DECIMAL(10,2) NOT NULL DEFAULT 0,
  nights INT UNSIGNED NOT NULL DEFAULT 1,
  discount DECIMAL(10,2) NOT NULL DEFAULT 0,
  total_price DECIMAL(10,2) NOT NULL DEFAULT 0,
  status ENUM('pending','awaiting_payment','paid','confirmed','completed','cancelled','refunded') NOT NULL DEFAULT 'pending',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_rb_hotel FOREIGN KEY (hotel_id) REFERENCES hotels (id) ON DELETE SET NULL,
  CONSTRAINT fk_rb_room FOREIGN KEY (room_id) REFERENCES hotel_rooms (id) ON DELETE SET NULL,
  CONSTRAINT fk_rb_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  UNIQUE KEY uq_rb_code (booking_code),
  UNIQUE KEY uq_rb_ref (booking_reference),
  INDEX idx_rb_user (user_id),
  INDEX idx_rb_email (guest_email),
  INDEX idx_rb_status (status)
) ENGINE=InnoDB;

-- ============================================================
-- 3) PAYMENTS — upgrade for unified, gateway-ready architecture
-- ============================================================
-- Add missing columns (idempotent)
SET @c := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='payments' AND COLUMN_NAME='booking_reference');
SET @s := IF(@c=0, 'ALTER TABLE payments ADD COLUMN booking_reference VARCHAR(30) NULL AFTER booking_id', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;

SET @c := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='payments' AND COLUMN_NAME='payment_method');
SET @s := IF(@c=0, 'ALTER TABLE payments ADD COLUMN payment_method VARCHAR(50) NULL AFTER currency', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;

SET @c := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='payments' AND COLUMN_NAME='gateway_response');
SET @s := IF(@c=0, 'ALTER TABLE payments ADD COLUMN gateway_response TEXT NULL AFTER transaction_reference', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;

-- CyberSource readiness placeholders — NO API calls, schema only
SET @c := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='payments' AND COLUMN_NAME='authorization_code');
SET @s := IF(@c=0, 'ALTER TABLE payments ADD COLUMN authorization_code VARCHAR(190) NULL AFTER transaction_reference', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;

SET @c := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='payments' AND COLUMN_NAME='payment_token');
SET @s := IF(@c=0, 'ALTER TABLE payments ADD COLUMN payment_token VARCHAR(255) NULL AFTER authorization_code', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;

-- Expand payment status ENUM: pending, authorized, paid, failed, cancelled, refunded
SET @s := (SELECT IF(
  (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='payments' AND COLUMN_NAME='status' AND COLUMN_TYPE LIKE '%authorized%') = 0,
  'ALTER TABLE payments MODIFY COLUMN status ENUM(''pending'',''authorized'',''paid'',''failed'',''cancelled'',''refunded'') NOT NULL DEFAULT ''pending''',
  'SELECT 1'));
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;

-- Existing payments backfill booking_reference from the referenced booking table
UPDATE payments p
  LEFT JOIN bookings b ON p.booking_type='transfer' AND b.id = p.booking_id
  SET p.booking_reference = b.booking_reference
  WHERE p.booking_type='transfer' AND p.booking_reference IS NULL AND b.id IS NOT NULL;
UPDATE payments p
  LEFT JOIN weroad_bookings b ON p.booking_type='tour' AND b.id = p.booking_id
  SET p.booking_reference = b.booking_reference
  WHERE p.booking_type='tour' AND p.booking_reference IS NULL AND b.id IS NOT NULL;
UPDATE payments p
  LEFT JOIN hotel_bookings b ON p.booking_type='hotel' AND b.id = p.booking_id
  SET p.booking_reference = b.booking_reference
  WHERE p.booking_type='hotel' AND p.booking_reference IS NULL AND b.id IS NOT NULL;
UPDATE payments p
  LEFT JOIN event_bookings b ON p.booking_type='event' AND b.id = p.booking_id
  SET p.booking_reference = b.booking_reference
  WHERE p.booking_type='event' AND p.booking_reference IS NULL AND b.id IS NOT NULL;
UPDATE payments p
  LEFT JOIN room_bookings b ON p.booking_type='room' AND b.id = p.booking_id
  SET p.booking_reference = b.booking_reference
  WHERE p.booking_type='room' AND p.booking_reference IS NULL AND b.id IS NOT NULL;

-- ============================================================
-- 4) PAYMENT TRANSACTIONS (gateway abstraction + webhooks)
--    One payment can have many gateway transactions.
-- ============================================================
CREATE TABLE IF NOT EXISTS payment_transactions (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  payment_id INT UNSIGNED NOT NULL,
  user_id INT UNSIGNED NULL,
  booking_type VARCHAR(20) NOT NULL,
  booking_reference VARCHAR(30) NULL,
  gateway VARCHAR(50) NULL,
  transaction_type ENUM('authorize','capture','sale','refund','void','webhook') NOT NULL DEFAULT 'sale',
  transaction_reference VARCHAR(190) NULL,
  amount DECIMAL(10,2) NOT NULL DEFAULT 0,
  currency VARCHAR(3) NOT NULL DEFAULT 'USD',
  status ENUM('pending','processing','authorized','completed','failed','cancelled','refunded') NOT NULL DEFAULT 'pending',
  request_payload TEXT NULL,
  response_payload TEXT NULL,
  webhook_payload TEXT NULL,
  ip_address VARCHAR(45) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_pt_payment FOREIGN KEY (payment_id) REFERENCES payments (id) ON DELETE CASCADE,
  INDEX idx_pt_payment (payment_id),
  INDEX idx_pt_reference (booking_reference),
  INDEX idx_pt_gateway_ref (gateway, transaction_reference)
) ENGINE=InnoDB;

-- ============================================================
-- 5) INVOICES (generic, reusable for all booking types)
-- ============================================================
CREATE TABLE IF NOT EXISTS invoices (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  booking_type ENUM('transfer','tour','hotel','room','event','taxi') NOT NULL,
  booking_id INT UNSIGNED NOT NULL,
  booking_reference VARCHAR(30) NULL,
  invoice_number VARCHAR(30) NOT NULL UNIQUE,
  subtotal DECIMAL(10,2) NOT NULL DEFAULT 0,
  tax_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
  discount_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
  total_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
  currency VARCHAR(3) NOT NULL DEFAULT 'USD',
  status ENUM('draft','issued','paid','void','cancelled') NOT NULL DEFAULT 'draft',
  issued_at DATETIME NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_inv_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  INDEX idx_inv_user (user_id),
  INDEX idx_inv_booking (booking_type, booking_id),
  INDEX idx_inv_reference (booking_reference),
  INDEX idx_inv_status (status)
) ENGINE=InnoDB;

-- ============================================================
-- 6) BOOKING LOGS (audit timeline, generic for all types)
-- ============================================================
CREATE TABLE IF NOT EXISTS booking_logs (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  booking_type VARCHAR(20) NOT NULL,
  booking_id INT UNSIGNED NOT NULL,
  user_id INT UNSIGNED NULL,
  action VARCHAR(80) NOT NULL,
  description VARCHAR(255) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_bl_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL,
  INDEX idx_bl_booking (booking_type, booking_id),
  INDEX idx_bl_user (user_id),
  INDEX idx_bl_action (action),
  INDEX idx_bl_created (created_at)
) ENGINE=InnoDB;

-- ============================================================
-- NOTE: user_id is intentionally left NULLABLE on the booking
-- tables because the platform supports guest bookings (user_id
-- NULL + guest_name/guest_email/guest_phone). The existing
-- foreign keys use ON DELETE SET NULL, so NOT NULL is NOT
-- enforced here. Ownership is enforced at the application layer
-- (BookingRepository / BookingSummaryService / PaymentService).

-- ============================================================
-- 8) ACCOUNT AREA TRANSLATIONS (EN/AR) — future dashboards
-- ============================================================
INSERT IGNORE INTO translations (`key`, lang, `value`, `group`) VALUES
-- ---- PAYMENT STATUSES ----
('account.status_awaiting_payment', 'en', 'Awaiting Payment', 'account'),
('account.status_awaiting_payment', 'ar', 'في انتظار الدفع', 'account'),
('account.status_paid', 'en', 'Paid', 'account'),
('account.status_paid', 'ar', 'مدفوع', 'account'),
('account.status_completed', 'en', 'Completed', 'account'),
('account.status_completed', 'ar', 'مكتمل', 'account'),
('account.status_refunded', 'en', 'Refunded', 'account'),
('account.status_refunded', 'ar', 'مسترجع', 'account'),
('account.status_authorized', 'en', 'Authorized', 'account'),
('account.status_authorized', 'ar', 'مصرح به', 'account'),
('account.status_failed', 'en', 'Failed', 'account'),
('account.status_failed', 'ar', 'فشل', 'account'),
('account.status_processing', 'en', 'Processing', 'account'),
('account.status_processing', 'ar', 'قيد المعالجة', 'account'),

-- ---- INVOICE STATUSES ----
('account.status_draft', 'en', 'Draft', 'account'),
('account.status_draft', 'ar', 'مسودة', 'account'),
('account.status_issued', 'en', 'Issued', 'account'),
('account.status_issued', 'ar', 'صادر', 'account'),
('account.status_void', 'en', 'Void', 'account'),
('account.status_void', 'ar', 'ملغى', 'account'),

-- ---- TIMELINE ACTIONS ----
('timeline.booking_created', 'en', 'Booking Created', 'account'),
('timeline.booking_created', 'ar', 'تم إنشاء الحجز', 'account'),
('timeline.payment_started', 'en', 'Payment Started', 'account'),
('timeline.payment_started', 'ar', 'بدأ الدفع', 'account'),
('timeline.payment_authorized', 'en', 'Payment Authorized', 'account'),
('timeline.payment_authorized', 'ar', 'تم التصريح بالدفع', 'account'),
('timeline.payment_completed', 'en', 'Payment Completed', 'account'),
('timeline.payment_completed', 'ar', 'اكتمل الدفع', 'account'),
('timeline.booking_confirmed', 'en', 'Booking Confirmed', 'account'),
('timeline.booking_confirmed', 'ar', 'تم تأكيد الحجز', 'account'),
('timeline.booking_cancelled', 'en', 'Booking Cancelled', 'account'),
('timeline.booking_cancelled', 'ar', 'تم إلغاء الحجز', 'account'),
('timeline.refund_issued', 'en', 'Refund Issued', 'account'),
('timeline.refund_issued', 'ar', 'تم إصدار الاسترداد', 'account'),

-- ---- PAYMENT / INVOICE / TIMELINE SECTIONS ----
('account.payment_status', 'en', 'Payment Status', 'account'),
('account.payment_status', 'ar', 'حالة الدفع', 'account'),
('account.invoice_status', 'en', 'Invoice Status', 'account'),
('account.invoice_status', 'ar', 'حالة الفاتورة', 'account'),
('account.invoice_number', 'en', 'Invoice Number', 'account'),
('account.invoice_number', 'ar', 'رقم الفاتورة', 'account'),
('account.timeline', 'en', 'Booking Timeline', 'account'),
('account.timeline', 'ar', 'الجدول الزمني للحجز', 'account'),
('account.payment_reference', 'en', 'Payment Reference', 'account'),
('account.payment_reference', 'ar', 'مرجع الدفع', 'account'),
('account.payment_method', 'en', 'Payment Method', 'account'),
('account.payment_method', 'ar', 'طريقة الدفع', 'account'),
('account.my_payments', 'en', 'My Payments', 'account'),
('account.my_payments', 'ar', 'مدفوعاتي', 'account'),
('account.my_invoices', 'en', 'My Invoices', 'account'),
('account.my_invoices', 'ar', 'فواتيري', 'account'),
('account.booking_reference', 'en', 'Booking Reference', 'account'),
('account.booking_reference', 'ar', 'مرجع الحجز', 'account'),
('account.service_name', 'en', 'Service', 'account'),
('account.service_name', 'ar', 'الخدمة', 'account'),
('account.customer', 'en', 'Customer', 'account'),
('account.customer', 'ar', 'العميل', 'account'),
('account.created_date', 'en', 'Created Date', 'account'),
('account.created_date', 'ar', 'تاريخ الإنشاء', 'account'),
('account.bookings_count', 'en', 'Total Bookings', 'account'),
('account.bookings_count', 'ar', 'إجمالي الحجوزات', 'account'),
('account.revenue', 'en', 'Revenue', 'account'),
('account.revenue', 'ar', 'الإيرادات', 'account'),
('account.pending_payments', 'en', 'Pending Payments', 'account'),
('account.pending_payments', 'ar', 'المدفوعات المعلقة', 'account'),
('account.cancelled_bookings', 'en', 'Cancelled Bookings', 'account'),
('account.cancelled_bookings', 'ar', 'الحجوزات الملغاة', 'account'),
('account.booking_summary', 'en', 'Booking Summary', 'account'),
('account.booking_summary', 'ar', 'ملخص الحجز', 'account');

-- ============================================================
-- 9) ACCOUNT AREA NAV PREPARATION (future My Payments / My Invoices)
-- ============================================================
INSERT IGNORE INTO menu_items (menu, parent_id, label, url, sort_order, is_active)
SELECT 'account', 0, 'My Payments', 'account/payments.php', 30, 1
WHERE NOT EXISTS (SELECT 1 FROM menu_items WHERE menu='account' AND url='account/payments.php');
INSERT IGNORE INTO menu_items (menu, parent_id, label, url, sort_order, is_active)
SELECT 'account', 0, 'My Invoices', 'account/invoices.php', 31, 1
WHERE NOT EXISTS (SELECT 1 FROM menu_items WHERE menu='account' AND url='account/invoices.php');
