-- ============================================================
-- GAIA TOURS & TRAVEL — Dynamic Data Audit — Migration #3
-- ------------------------------------------------------------
-- Completes the remaining translation keys (EN/AR) required for
-- the GAIA Night hero, the Tours module (weroad) pages, cookie
-- toast, and search UI. Safe to run repeatedly.
-- ============================================================
USE gaia_tours;

INSERT IGNORE INTO translations (`key`, lang, `value`, `group`) VALUES
-- cookie toast split text
('home.cookie_text', 'en', 'We use cookies to personalize your experience.', 'home'),
('home.cookie_text', 'ar', 'نستخدم ملفات الارتباط لتخصيص تجربتك.', 'home'),
('home.cookie_policy', 'en', 'Read our Cookie Policy', 'home'),
('home.cookie_policy', 'ar', 'اقرأ سياسة ملفات الارتباط', 'home'),

-- ------------------------------------------------------------------
-- TOURS MODULE — Homepage (weroad/index.php)
-- ------------------------------------------------------------------
('tours.hero_title', 'en', 'Discover Jordan.<br>Explore with GAIA Tours.', 'tours'),
('tours.hero_title', 'ar', 'اكتشف الأردن.<br>استكشف مع غايا جولات.', 'tours'),
('tours.hero_sub', 'en', 'Small group tours, family travel and private experiences across Petra, Wadi Rum, the Dead Sea and Amman — one trusted GAIA platform.', 'tours'),
('tours.hero_sub', 'ar', 'جولات جماعية صغيرة وسفر عائلي وتجارب خاصة في البتراء ووادي رم والبحر الميت وعمّان — منصة غايا الموثوقة.', 'tours'),
('tours.search_placeholder', 'en', 'Where do you want to go?', 'tours'),
('tours.search_placeholder', 'ar', 'إلى أين تريد الذهاب؟', 'tours'),
('tours.search_btn', 'en', 'Search', 'tours'),
('tours.search_btn', 'ar', 'بحث', 'tours'),
('tours.promo_title', 'en', 'Waiting for your next adventure?', 'tours'),
('tours.promo_title', 'ar', 'هل تنتظر مغامرتك القادمة؟', 'tours'),
('tours.promo_text', 'en', 'Book now and split the cost into interest-free installments. Your seat, your squad, your story.', 'tours'),
('tours.promo_text', 'ar', 'احجز الآن واقسم التكلفة إلى أقساط بدون فوائد. مقعدك، رفقتك، قصتك.', 'tours'),
('tours.book_now', 'en', 'Book now', 'tours'),
('tours.book_now', 'ar', 'احجز الآن', 'tours'),
('tours.deals_title', 'en', 'Last minute deals', 'tours'),
('tours.deals_title', 'ar', 'عروض اللحظة الأخيرة', 'tours'),
('tours.see_all', 'en', 'See all', 'tours'),
('tours.see_all', 'ar', 'عرض الكل', 'tours'),
('tours.category_title', 'en', 'The group tour that''s right for you', 'tours'),
('tours.category_title', 'ar', 'الجولة الجماعية المناسبة لك', 'tours'),
('tours.loved_title', 'en', 'The most loved adventures', 'tours'),
('tours.loved_title', 'ar', 'المغامرات الأكثر حبًا', 'tours'),
('tours.trustpilot_title', 'en', 'Rated Excellent on Trustpilot', 'tours'),
('tours.trustpilot_title', 'ar', 'مقيم بممتاز على ترستبيلوت', 'tours'),
('tours.cta_title', 'en', 'Ready to start the adventure?', 'tours'),
('tours.cta_title', 'ar', 'مستعد لبدء المغامرة؟', 'tours'),
('tours.explore_trips', 'en', 'Explore trips', 'tours'),
('tours.explore_trips', 'ar', 'استكشف الجولات', 'tours'),
('tours.price_from', 'en', 'From <b>${price}</b>', 'tours'),
('tours.price_from', 'ar', 'من <b>${price}</b>', 'tours'),
('tours.days', 'en', '{days} days', 'tours'),
('tours.days', 'ar', '{days} أيام', 'tours'),
('tours.no_deals', 'en', 'No deals available right now.', 'tours'),
('tours.no_deals', 'ar', 'لا توجد عروض متاحة حاليًا.', 'tours'),
('tours.no_categories', 'en', 'Categories coming soon.', 'tours'),
('tours.no_categories', 'ar', 'الفئات قريبًا.', 'tours'),
('tours.no_reviews', 'en', 'Reviews coming soon.', 'tours'),
('tours.no_reviews', 'ar', 'التقييمات قريبًا.', 'tours'),

-- ------------------------------------------------------------------
-- TOURS MODULE — Search (weroad/search.php)
-- ------------------------------------------------------------------
('tours.search_where', 'en', 'Where', 'tours'),
('tours.search_where', 'ar', 'إلى أين', 'tours'),
('tours.search_dest', 'en', 'Search destination', 'tours'),
('tours.search_dest', 'ar', 'ابحث عن وجهة', 'tours'),
('tours.search_when', 'en', 'When', 'tours'),
('tours.search_when', 'ar', 'متى', 'tours'),
('tours.chip_age', 'en', 'Age range', 'tours'),
('tours.chip_age', 'ar', 'الفئة العمرية', 'tours'),
('tours.chip_flights', 'en', 'Flights from', 'tours'),
('tours.chip_flights', 'ar', 'رحلات الطيران من', 'tours'),
('tours.chip_price', 'en', 'Price', 'tours'),
('tours.chip_price', 'ar', 'السعر', 'tours'),
('tours.chip_days', 'en', 'Number of days', 'tours'),
('tours.chip_days', 'ar', 'عدد الأيام', 'tours'),
('tours.chip_effort', 'en', 'Physical effort', 'tours'),
('tours.chip_effort', 'ar', 'الجهد البدني', 'tours'),
('tours.chip_type', 'en', 'Trip type', 'tours'),
('tours.chip_type', 'ar', 'نوع الرحلة', 'tours'),
('tours.chip_private', 'en', 'Private room', 'tours'),
('tours.chip_private', 'ar', 'غرفة خاصة', 'tours'),
('tours.chip_filters', 'en', 'Filters', 'tours'),
('tours.chip_filters', 'ar', 'التصفية', 'tours'),
('tours.view_by', 'en', 'View by', 'tours'),
('tours.view_by', 'ar', 'عرض حسب', 'tours'),
('tours.trips_tab', 'en', 'Trips', 'tours'),
('tours.trips_tab', 'ar', 'الجولات', 'tours'),
('tours.dates_tab', 'en', 'Dates', 'tours'),
('tours.dates_tab', 'ar', 'التواريخ', 'tours'),
('tours.show_maps', 'en', 'Show maps', 'tours'),
('tours.show_maps', 'ar', 'إظهار الخرائط', 'tours'),
('tours.results_found', 'en', '{count} trip(s) found', 'tours'),
('tours.results_found', 'ar', 'تم العثور على {count} جولة', 'tours'),
('tours.show', 'en', 'Show {per}', 'tours'),
('tours.show', 'ar', 'عرض {per}', 'tours'),
('tours.page_of', 'en', 'Page {page} of {total}', 'tours'),
('tours.page_of', 'ar', 'صفحة {page} من {total}', 'tours'),
('tours.prev', 'en', 'Previous', 'tours'),
('tours.prev', 'ar', 'السابق', 'tours'),
('tours.next', 'en', 'Next', 'tours'),
('tours.next', 'ar', 'التالي', 'tours'),
('tours.compare', 'en', 'Compare', 'tours'),
('tours.compare', 'ar', 'مقارنة', 'tours'),
('tours.see_dates', 'en', 'See departure dates', 'tours'),
('tours.see_dates', 'ar', 'عرض تواريخ المغادرة', 'tours'),
('tours.no_results', 'en', 'No trips match your filters. Try adjusting your search.', 'tours'),
('tours.no_results', 'ar', 'لا توجد جولات تطابق تصفيتك. حاول تعديل بحثك.', 'tours'),

-- ------------------------------------------------------------------
-- TOURS MODULE — Trip detail (weroad/trip.php)
-- ------------------------------------------------------------------
('tours.trip_home', 'en', 'Home', 'tours'),
('tours.trip_home', 'ar', 'الرئيسية', 'tours'),
('tours.trip_not_found', 'en', 'Trip not found', 'tours'),
('tours.trip_not_found', 'ar', 'الجولة غير موجودة', 'tours'),
('tours.trip_not_found_sub', 'en', 'The trip you are looking for does not exist.', 'tours'),
('tours.trip_not_found_sub', 'ar', 'الجولة التي تبحث عنها غير موجودة.', 'tours'),
('tours.trip_browse', 'en', 'Browse trips', 'tours'),
('tours.trip_browse', 'ar', 'تصفح الجولات', 'tours'),
('tours.trip_reviews', 'en', '{rating} ({reviews} reviews)', 'tours'),
('tours.trip_reviews', 'ar', '{rating} ({reviews} تقييم)', 'tours'),
('tours.trip_max_people', 'en', 'Max {max} people', 'tours'),
('tours.trip_max_people', 'ar', 'بحد أقصى {max} أشخاص', 'tours'),
('tours.trip_effort', 'en', '{effort} effort', 'tours'),
('tours.trip_effort', 'ar', 'مجهود {effort}', 'tours'),
('tours.trip_fit_title', 'en', 'Is this trip for me?', 'tours'),
('tours.trip_fit_title', 'ar', 'هل هذه الجولة مناسبة لي؟', 'tours'),
('tours.trip_age', 'en', 'Age range', 'tours'),
('tours.trip_age', 'ar', 'الفئة العمرية', 'tours'),
('tours.trip_physical', 'en', 'Physical effort', 'tours'),
('tours.trip_physical', 'ar', 'الجهد البدني', 'tours'),
('tours.trip_comfort', 'en', 'Comfort level', 'tours'),
('tours.trip_comfort', 'ar', 'مستوى الراحة', 'tours'),
('tours.trip_accommodation', 'en', 'Accommodation', 'tours'),
('tours.trip_accommodation', 'ar', 'الإقامة', 'tours'),
('tours.trip_itinerary', 'en', 'Itinerary', 'tours'),
('tours.trip_itinerary', 'ar', 'خط السير', 'tours'),
('tours.day_label', 'en', 'Day {day}', 'tours'),
('tours.day_label', 'ar', 'اليوم {day}', 'tours'),
('tours.trip_included', 'en', 'What''s included', 'tours'),
('tours.trip_included', 'ar', 'ما الذي تشمله الجولة', 'tours'),
('tours.included_list', 'en', 'Included', 'tours'),
('tours.included_list', 'ar', 'مشمول', 'tours'),
('tours.not_included_list', 'en', 'Not included', 'tours'),
('tours.not_included_list', 'ar', 'غير مشمول', 'tours'),
('tours.trip_optional', 'en', 'Optional activities', 'tours'),
('tours.trip_optional', 'ar', 'أنشطة اختيارية', 'tours'),
('tours.trip_optional_sub', 'en', 'Bookable directly with your Group Leader during the trip.', 'tours'),
('tours.trip_optional_sub', 'ar', 'يمكن حجزها مباشرة مع قائد المجموعة أثناء الرحلة.', 'tours'),
('tours.trip_why', 'en', 'Why GAIA Tours', 'tours'),
('tours.trip_why', 'ar', 'لماذا غايا جولات', 'tours'),
('tours.trip_faqs', 'en', 'FAQs — Frequently Asked Questions', 'tours'),
('tours.trip_faqs', 'ar', 'الأسئلة الشائعة', 'tours'),
('tours.trip_from', 'en', 'From', 'tours'),
('tours.trip_from', 'ar', 'من', 'tours'),
('tours.trip_see_dates', 'en', 'See dates', 'tours'),
('tours.trip_see_dates', 'ar', 'عرض التواريخ', 'tours'),
('tours.trip_spots_left', 'en', 'Only {spots} spots left for {month}', 'tours'),
('tours.trip_spots_left', 'ar', 'تبقى {spots} مقاعد فقط لشهر {month}', 'tours'),
('tours.trip_departures', 'en', '{count} departure date(s) available', 'tours'),
('tours.trip_departures', 'ar', '{count} تاريخ مغادرة متاح', 'tours'),
('tours.trip_no_departures', 'en', 'No upcoming departures.', 'tours'),
('tours.trip_no_departures', 'ar', 'لا توجد مغادرات قادمة.', 'tours'),
('tours.trip_travellers', 'en', 'Over {count} GAIA travellers have done this trip', 'tours'),
('tours.trip_travellers', 'ar', 'أكثر من {count} مسافر مع غايا قاموا بهذه الجولة', 'tours'),
('tours.trip_installments', 'en', 'Interest-free installments', 'tours'),
('tours.trip_installments', 'ar', 'أقساط بدون فوائد', 'tours'),
('tours.trip_insurance', 'en', 'Medical &amp; baggage insurance included', 'tours'),
('tours.trip_insurance', 'ar', 'تأمين طبي وأمتعة مشمول', 'tours'),
('tours.trip_ask', 'en', 'Ask an expert', 'tours'),
('tours.trip_ask', 'ar', 'اسأل خبيرًا', 'tours'),

-- ------------------------------------------------------------------
-- TOURS MODULE — Booking (weroad/booking.php)
-- ------------------------------------------------------------------
('tours.booking_not_found', 'en', 'Trip not found', 'tours'),
('tours.booking_not_found', 'ar', 'الجولة غير موجودة', 'tours'),
('tours.booking_not_found_sub', 'en', 'Please start again from the search page.', 'tours'),
('tours.booking_not_found_sub', 'ar', 'يرجى البدء مرة أخرى من صفحة البحث.', 'tours'),
('tours.booking_browse', 'en', 'Browse trips', 'tours'),
('tours.booking_browse', 'ar', 'تصفح الجولات', 'tours'),
('tours.booking_no_departures', 'en', 'No departures available.', 'tours'),
('tours.booking_no_departures', 'ar', 'لا توجد مغادرات متاحة.', 'tours'),
('tours.booking_step1', 'en', 'Booking', 'tours'),
('tours.booking_step1', 'ar', 'الحجز', 'tours'),
('tours.booking_step2', 'en', 'Travellers details', 'tours'),
('tours.booking_step2', 'ar', 'تفاصيل المسافرين', 'tours'),
('tours.booking_step3', 'en', 'Account data', 'tours'),
('tours.booking_step3', 'ar', 'بيانات الحساب', 'tours'),
('tours.booking_step4', 'en', 'Payment', 'tours'),
('tours.booking_step4', 'ar', 'الدفع', 'tours'),
('tours.booking_mandatory', 'en', 'Mandatory fields *', 'tours'),
('tours.booking_mandatory', 'ar', 'حقول إلزامية *', 'tours'),
('tours.booking_fullname', 'en', 'Full name *', 'tours'),
('tours.booking_fullname', 'ar', 'الاسم الكامل *', 'tours'),
('tours.booking_email', 'en', 'Email *', 'tours'),
('tours.booking_email', 'ar', 'البريد الإلكتروني *', 'tours'),
('tours.booking_phone', 'en', 'Phone', 'tours'),
('tours.booking_phone', 'ar', 'الهاتف', 'tours'),
('tours.booking_who', 'en', 'Who are you booking for? *', 'tours'),
('tours.booking_who', 'ar', 'لمن تحجز؟ *', 'tours'),
('tours.booking_why_gender', 'en', 'Why we ask for your gender', 'tours'),
('tours.booking_why_gender', 'ar', 'لماذا نسأل عن جنسك', 'tours'),
('tours.booking_female', 'en', 'FEMALE', 'tours'),
('tours.booking_female', 'ar', 'أنثى', 'tours'),
('tours.booking_male', 'en', 'MALE', 'tours'),
('tours.booking_male', 'ar', 'ذكر', 'tours'),
('tours.booking_included', 'en', 'Included in your trip', 'tours'),
('tours.booking_included', 'ar', 'مشمول في جولتك', 'tours'),
('tours.booking_included_sub', 'en', 'These options are already included in the price', 'tours'),
('tours.booking_included_sub', 'ar', 'هذه الخيارات مشمولة بالفعل في السعر', 'tours'),
('tours.booking_mixed', 'en', 'I''m OK with a mixed gender room', 'tours'),
('tours.booking_mixed', 'ar', 'لا مانع لدي من غرفة مختلطة', 'tours'),
('tours.booking_insurance_title', 'en', 'Medical and Baggage Insurance included', 'tours'),
('tours.booking_insurance_title', 'ar', 'تأمين طبي وأمتعة مشمول', 'tours'),
('tours.booking_options', 'en', 'Options and extras', 'tours'),
('tours.booking_options', 'ar', 'الخيارات والإضافات', 'tours'),
('tours.booking_promo', 'en', 'Promo code', 'tours'),
('tours.booking_promo', 'ar', 'رمز الخصم', 'tours'),
('tours.booking_promo_ph', 'en', 'e.g. WEROAD10', 'tours'),
('tours.booking_promo_ph', 'ar', 'مثال: WEROAD10', 'tours'),
('tours.booking_apply', 'en', 'Apply', 'tours'),
('tours.booking_apply', 'ar', 'تطبيق', 'tours'),
('tours.booking_continue', 'en', 'Continue', 'tours'),
('tours.booking_continue', 'ar', 'متابعة', 'tours'),
('tours.booking_your_trip', 'en', 'Your trip', 'tours'),
('tours.booking_your_trip', 'ar', 'جولتك', 'tours'),
('tours.booking_from', 'en', 'From', 'tours'),
('tours.booking_from', 'ar', 'من', 'tours'),
('tours.booking_to', 'en', 'To', 'tours'),
('tours.booking_to', 'ar', 'إلى', 'tours'),
('tours.booking_available', 'en', 'Available', 'tours'),
('tours.booking_available', 'ar', 'متاح', 'tours'),
('tours.booking_trip_price', 'en', 'Trip price', 'tours'),
('tours.booking_trip_price', 'ar', 'سعر الجولة', 'tours'),
('tours.booking_flex_line', 'en', 'Flexible cancellation', 'tours'),
('tours.booking_flex_line', 'ar', 'إلغاء مرن', 'tours'),
('tours.booking_room_line', 'en', 'Private room', 'tours'),
('tours.booking_room_line', 'ar', 'غرفة خاصة', 'tours'),
('tours.booking_discount', 'en', 'Discount', 'tours'),
('tours.booking_discount', 'ar', 'الخصم', 'tours'),
('tours.booking_total', 'en', 'Total', 'tours'),
('tours.booking_total', 'ar', 'الإجمالي', 'tours'),
('tours.booking_installments', 'en', 'Interest-free installments', 'tours'),
('tours.booking_installments', 'ar', 'أقساط بدون فوائد', 'tours'),
('tours.booking_over_travellers', 'en', 'Over <strong>{count}</strong> GAIA travellers have already done this trip', 'tours'),
('tours.booking_over_travellers', 'ar', 'أكثر من <strong>{count}</strong> مسافر مع غايا قاموا بهذه الجولة', 'tours'),
('tours.booking_need_help', 'en', 'Do you need help?', 'tours'),
('tours.booking_need_help', 'ar', 'هل تحتاج مساعدة؟', 'tours'),
('tours.booking_ask', 'en', 'Ask an expert', 'tours'),
('tours.booking_ask', 'ar', 'اسأل خبيرًا', 'tours');

