-- ============================================================
-- GAIA TOURS & TRAVEL — Customer Dashboard
-- Migration #12
-- ------------------------------------------------------------
-- Objective: Add all missing EN/AR translation keys for the
-- complete customer dashboard layer.
--
-- Covers:
--   * Dashboard quick stats + recent activity + quick actions
--   * Unified bookings table (filters, pagination)
--   * Booking details (by reference)
--   * Payments (filters, pagination)
--   * Invoices (view/print)
--   * Profile (avatar upload)
--   * Security page
--   * Booking type labels
--
-- Safe to run repeatedly (INSERT IGNORE).
-- ============================================================
USE gaia_tours;

INSERT IGNORE INTO translations (`key`, lang, `value`, `group`) VALUES

-- ============================================================
-- DASHBOARD — QUICK STATS
-- ============================================================
('account.total_bookings',        'en', 'Total Bookings', 'account'),
('account.total_bookings',        'ar', 'إجمالي الحجوزات', 'account'),
('account.upcoming_trips',        'en', 'Upcoming Trips', 'account'),
('account.upcoming_trips',        'ar', 'الرحلات القادمة', 'account'),
('account.completed_bookings',    'en', 'Completed Bookings', 'account'),
('account.completed_bookings',    'ar', 'الحجوزات المكتملة', 'account'),
('account.pending_payments',      'en', 'Pending Payments', 'account'),
('account.pending_payments',      'ar', 'المدفوعات المعلقة', 'account'),

-- ============================================================
-- DASHBOARD — RECENT ACTIVITY / UPCOMING / QUICK ACTIONS
-- ============================================================
('account.recent_activity',       'en', 'Recent Activity', 'account'),
('account.recent_activity',       'ar', 'النشاط الأخير', 'account'),
('account.no_activity',           'en', 'No recent activity yet.', 'account'),
('account.no_activity',           'ar', 'لا يوجد نشاط حديث بعد.', 'account'),
('account.upcoming_reservations', 'en', 'Upcoming Reservations', 'account'),
('account.upcoming_reservations', 'ar', 'الحجوزات القادمة', 'account'),
('account.no_upcoming',           'en', 'No upcoming reservations.', 'account'),
('account.no_upcoming',           'ar', 'لا توجد حجوزات قادمة.', 'account'),
('account.quick_actions',         'en', 'Quick Actions', 'account'),
('account.quick_actions',         'ar', 'إجراءات سريعة', 'account'),
('account.browse_tours',          'en', 'Browse Tours', 'account'),
('account.browse_tours',          'ar', 'تصفح الجولات', 'account'),
('account.browse_hotels',         'en', 'Browse Hotels', 'account'),
('account.browse_hotels',         'ar', 'تصفح الفنادق', 'account'),
('account.browse_events',         'en', 'Browse Events', 'account'),
('account.browse_events',         'ar', 'تصفح الفعاليات', 'account'),
('account.book_transfer',         'en', 'Book Transfer', 'account'),
('account.book_transfer',         'ar', 'احجز نقل', 'account'),
('account.view_all_bookings',     'en', 'View All Bookings', 'account'),
('account.view_all_bookings',     'ar', 'عرض جميع الحجوزات', 'account'),

-- ============================================================
-- UNIFIED BOOKINGS TABLE
-- ============================================================
('account.all_types',             'en', 'All Types', 'account'),
('account.all_types',             'ar', 'جميع الأنواع', 'account'),
('account.filter_type',           'en', 'Filter by type', 'account'),
('account.filter_type',           'ar', 'تصفية حسب النوع', 'account'),
('account.filter_status',         'en', 'Filter by status', 'account'),
('account.filter_status',         'ar', 'تصفية حسب الحالة', 'account'),
('account.all_statuses',          'en', 'All Statuses', 'account'),
('account.all_statuses',          'ar', 'كل الحالات', 'account'),
('account.apply_filters',         'en', 'Apply', 'account'),
('account.apply_filters',         'ar', 'تطبيق', 'account'),
('account.reset_filters',         'en', 'Reset', 'account'),
('account.reset_filters',         'ar', 'إعادة تعيين', 'account'),
('account.booking_type',          'en', 'Type', 'account'),
('account.booking_type',          'ar', 'النوع', 'account'),
('account.booking_date',          'en', 'Booking Date', 'account'),
('account.booking_date',          'ar', 'تاريخ الحجز', 'account'),
('account.amount',                'en', 'Amount', 'account'),
('account.amount',                'ar', 'المبلغ', 'account'),
('account.status',                'en', 'Status', 'account'),
('account.status',                'ar', 'الحالة', 'account'),
('account.actions',               'en', 'Actions', 'account'),
('account.actions',               'ar', 'الإجراءات', 'account'),
('account.view_details',          'en', 'View Details', 'account'),
('account.view_details',          'ar', 'عرض التفاصيل', 'account'),
('account.type_tour',             'en', 'Tour', 'account'),
('account.type_tour',             'ar', 'جولة', 'account'),
('account.type_hotel',            'en', 'Hotel', 'account'),
('account.type_hotel',            'ar', 'فندق', 'account'),
('account.type_room',             'en', 'Room', 'account'),
('account.type_room',             'ar', 'غرفة', 'account'),
('account.type_event',            'en', 'Event', 'account'),
('account.type_event',            'ar', 'فعالية', 'account'),
('account.type_transfer',         'en', 'Transfer', 'account'),
('account.type_transfer',         'ar', 'نقل', 'account'),
('account.type_taxi',             'en', 'Taxi', 'account'),
('account.type_taxi',             'ar', 'سيارة أجرة', 'account'),
('account.status_pending',        'en', 'Pending', 'account'),
('account.status_pending',        'ar', 'قيد الانتظار', 'account'),
('account.status_cancelled',      'en', 'Cancelled', 'account'),
('account.status_cancelled',      'ar', 'ملغي', 'account'),
('account.status_confirmed',      'en', 'Confirmed', 'account'),
('account.status_confirmed',      'ar', 'مؤكد', 'account'),
('account.status_awaiting_payment','en', 'Awaiting Payment', 'account'),
('account.status_awaiting_payment','ar', 'في انتظار الدفع', 'account'),
('account.status_paid',           'en', 'Paid', 'account'),
('account.status_paid',           'ar', 'مدفوع', 'account'),
('account.status_completed',      'en', 'Completed', 'account'),
('account.status_completed',      'ar', 'مكتمل', 'account'),
('account.status_refunded',       'en', 'Refunded', 'account'),
('account.status_refunded',       'ar', 'مسترجع', 'account'),

-- ============================================================
-- PAGINATION
-- ============================================================
('account.page',                  'en', 'Page', 'account'),
('account.page',                  'ar', 'صفحة', 'account'),
('account.of',                    'en', 'of', 'account'),
('account.of',                    'ar', 'من', 'account'),
('account.showing',               'en', 'Showing', 'account'),
('account.showing',               'ar', 'عرض', 'account'),
('account.to',                    'en', 'to', 'account'),
('account.to',                    'ar', 'إلى', 'account'),
('account.no_records',            'en', 'No records found.', 'account'),
('account.no_records',            'ar', 'لا توجد سجلات.', 'account'),
('account.prev',                  'en', 'Previous', 'account'),
('account.prev',                  'ar', 'السابق', 'account'),
('account.next',                  'en', 'Next', 'account'),
('account.next',                  'ar', 'التالي', 'account'),

-- ============================================================
-- BOOKING DETAILS (BY REFERENCE)
-- ============================================================
('account.booking_details',       'en', 'Booking Details', 'account'),
('account.booking_details',       'ar', 'تفاصيل الحجز', 'account'),
('account.reference',             'en', 'Reference', 'account'),
('account.reference',             'ar', 'المرجع', 'account'),
('account.type',                  'en', 'Type', 'account'),
('account.type',                  'ar', 'النوع', 'account'),
('account.created_at',            'en', 'Created', 'account'),
('account.created_at',            'ar', 'تاريخ الإنشاء', 'account'),
('account.service_details',       'en', 'Service Information', 'account'),
('account.service_details',       'ar', 'معلومات الخدمة', 'account'),
('account.customer_info',         'en', 'Customer Information', 'account'),
('account.customer_info',         'ar', 'معلومات العميل', 'account'),
('account.payment_info',          'en', 'Payment Information', 'account'),
('account.payment_info',          'ar', 'معلومات الدفع', 'account'),
('account.invoice_info',          'en', 'Invoice Information', 'account'),
('account.invoice_info',          'ar', 'معلومات الفاتورة', 'account'),
('account.price_breakdown',       'en', 'Price Breakdown', 'account'),
('account.price_breakdown',       'ar', 'تفاصيل السعر', 'account'),
('account.total',                 'en', 'Total', 'account'),
('account.total',                 'ar', 'الإجمالي', 'account'),
('account.unauthorized',          'en', 'Access Denied', 'account'),
('account.unauthorized',          'ar', 'تم رفض الوصول', 'account'),
('account.booking_not_found',     'en', 'Booking not found or you do not have access to it.', 'account'),
('account.booking_not_found',     'ar', 'الحجز غير موجود أو ليس لديك صلاحية الوصول إليه.', 'account'),
('account.back_to_bookings',      'en', 'Back to Bookings', 'account'),
('account.back_to_bookings',      'ar', 'العودة إلى الحجوزات', 'account'),
('account.guest_name',            'en', 'Guest Name', 'account'),
('account.guest_name',            'ar', 'اسم الضيف', 'account'),
('account.guest_email',           'en', 'Guest Email', 'account'),
('account.guest_email',           'ar', 'بريد الضيف', 'account'),
('account.guest_phone',           'en', 'Guest Phone', 'account'),
('account.guest_phone',           'ar', 'هاتف الضيف', 'account'),
('account.transaction_ref',       'en', 'Transaction Reference', 'account'),
('account.transaction_ref',       'ar', 'مرجع العملية', 'account'),
('account.currency',              'en', 'Currency', 'account'),
('account.currency',              'ar', 'العملة', 'account'),

-- ============================================================
-- PAYMENTS
-- ============================================================
('account.payment',               'en', 'Payment', 'account'),
('account.payment',               'ar', 'الدفع', 'account'),
('account.date',                  'en', 'Date', 'account'),
('account.date',                  'ar', 'التاريخ', 'account'),
('account.no_payments',           'en', 'No payments yet.', 'account'),
('account.no_payments',           'ar', 'لا توجد مدفوعات بعد.', 'account'),
('account.filter_pay_status',     'en', 'Filter by payment status', 'account'),
('account.filter_pay_status',     'ar', 'تصفية حسب حالة الدفع', 'account'),

-- ============================================================
-- INVOICES
-- ============================================================
('account.no_invoices',           'en', 'No invoices yet.', 'account'),
('account.no_invoices',           'ar', 'لا توجد فواتير بعد.', 'account'),
('account.invoice',               'en', 'Invoice', 'account'),
('account.invoice',               'ar', 'فاتورة', 'account'),
('account.invoice_status',        'en', 'Invoice Status', 'account'),
('account.invoice_status',        'ar', 'حالة الفاتورة', 'account'),
('account.issue_date',            'en', 'Issue Date', 'account'),
('account.issue_date',            'ar', 'تاريخ الإصدار', 'account'),
('account.view_invoice',          'en', 'View Invoice', 'account'),
('account.view_invoice',          'ar', 'عرض الفاتورة', 'account'),
('account.print_invoice',         'en', 'Print Invoice', 'account'),
('account.print_invoice',         'ar', 'طباعة الفاتورة', 'account'),
('account.invoice_details',       'en', 'Invoice Details', 'account'),
('account.invoice_details',       'ar', 'تفاصيل الفاتورة', 'account'),
('account.bill_to',               'en', 'Billed To', 'account'),
('account.bill_to',               'ar', 'فاتورة إلى', 'account'),
('account.subtotal',              'en', 'Subtotal', 'account'),
('account.subtotal',              'ar', 'المجموع الفرعي', 'account'),
('account.tax_amount',            'en', 'Tax', 'account'),
('account.tax_amount',            'ar', 'الضريبة', 'account'),
('account.discount_amount',       'en', 'Discount', 'account'),
('account.discount_amount',       'ar', 'الخصم', 'account'),
('account.total_amount',          'en', 'Total Amount', 'account'),
('account.total_amount',          'ar', 'المبلغ الإجمالي', 'account'),
('account.invoice_issued_on',     'en', 'Issued On', 'account'),
('account.invoice_issued_on',     'ar', 'صدر في', 'account'),
('account.print',                 'en', 'Print', 'account'),
('account.print',                 'ar', 'طباعة', 'account'),
('account.back_to_invoices',      'en', 'Back to Invoices', 'account'),
('account.back_to_invoices',      'ar', 'العودة إلى الفواتير', 'account'),
('account.invoice_not_found',     'en', 'Invoice not found or you do not have access to it.', 'account'),
('account.invoice_not_found',     'ar', 'الفاتورة غير موجودة أو ليس لديك صلاحية الوصول إليها.', 'account'),

-- ============================================================
-- PROFILE
-- ============================================================
('account.profile',               'en', 'Profile', 'account'),
('account.profile',               'ar', 'الملف الشخصي', 'account'),
('account.avatar',                'en', 'Avatar', 'account'),
('account.avatar',                'ar', 'الصورة الرمزية', 'account'),
('account.save_changes',          'en', 'Save Changes', 'account'),
('account.save_changes',          'ar', 'حفظ التغييرات', 'account'),
('account.profile_updated',       'en', 'Profile updated successfully.', 'account'),
('account.profile_updated',       'ar', 'تم تحديث الملف الشخصي بنجاح.', 'account'),
('account.choose_avatar',         'en', 'Choose an image', 'account'),
('account.choose_avatar',         'ar', 'اختر صورة', 'account'),
('account.avatar_hint',           'en', 'JPG, PNG or WEBP. Max 2MB.', 'account'),
('account.avatar_hint',           'ar', 'JPG أو PNG أو WEBP. بحد أقصى 2MB.', 'account'),
('account.avatar_invalid_type',   'en', 'Invalid image type. Allowed: JPG, PNG, WEBP.', 'account'),
('account.avatar_invalid_type',   'ar', 'نوع صورة غير صالح. المسموح: JPG, PNG, WEBP.', 'account'),
('account.avatar_too_large',      'en', 'Image is too large. Maximum size is 2MB.', 'account'),
('account.avatar_too_large',      'ar', 'الصورة كبيرة جداً. الحجم الأقصى هو 2MB.', 'account'),
('account.avatar_upload_error',   'en', 'Could not upload the avatar. Please try again.', 'account'),
('account.avatar_upload_error',   'ar', 'تعذر رفع الصورة الرمزية. حاول مرة أخرى.', 'account'),
('account.avatar_removed',        'en', 'Avatar removed.', 'account'),
('account.avatar_removed',        'ar', 'تمت إزالة الصورة الرمزية.', 'account'),

-- ============================================================
-- SECURITY
-- ============================================================
('account.security',              'en', 'Security', 'account'),
('account.security',              'ar', 'الأمان', 'account'),
('account.current_password',      'en', 'Current Password', 'account'),
('account.current_password',      'ar', 'كلمة المرور الحالية', 'account'),
('account.new_password',          'en', 'New Password', 'account'),
('account.new_password',          'ar', 'كلمة المرور الجديدة', 'account'),
('account.confirm_password',      'en', 'Confirm Password', 'account'),
('account.confirm_password',      'ar', 'تأكيد كلمة المرور', 'account'),
('account.change_password',       'en', 'Change Password', 'account'),
('account.change_password',       'ar', 'تغيير كلمة المرور', 'account'),
('account.security_info',         'en', 'Account Security Information', 'account'),
('account.security_info',         'ar', 'معلومات أمان الحساب', 'account'),
('account.last_login',            'en', 'Last Login', 'account'),
('account.last_login',            'ar', 'آخر تسجيل دخول', 'account'),
('account.email_verified',        'en', 'Email Verification', 'account'),
('account.email_verified',        'ar', 'توثيق البريد الإلكتروني', 'account'),
('account.verified',              'en', 'Verified', 'account'),
('account.verified',              'ar', 'موثق', 'account'),
('account.unverified',            'en', 'Unverified', 'account'),
('account.unverified',            'ar', 'غير موثق', 'account'),
('account.password_updated',      'en', 'Password updated successfully.', 'account'),
('account.password_updated',      'ar', 'تم تحديث كلمة المرور بنجاح.', 'account'),
('account.current_password_required', 'en', 'Current password is required.', 'account'),
('account.current_password_required', 'ar', 'كلمة المرور الحالية مطلوبة.', 'account'),
('account.password_min_length',   'en', 'Password must be at least {min} characters.', 'account'),
('account.password_min_length',   'ar', 'يجب أن تكون كلمة المرور {min} أحرف على الأقل.', 'account'),
('account.password_mismatch',     'en', 'New passwords do not match.', 'account'),
('account.password_mismatch',     'ar', 'كلمتا المرور الجديدتان غير متطابقتين.', 'account'),
('account.current_password_wrong','en', 'Current password is incorrect.', 'account'),
('account.current_password_wrong','ar', 'كلمة المرور الحالية غير صحيحة.', 'account'),
('account.password_same',         'en', 'New password must be different from the current password.', 'account'),
('account.password_same',         'ar', 'يجب أن تختلف كلمة المرور الجديدة عن الحالية.', 'account'),

-- ============================================================
-- ACCOUNT COMMON
-- ============================================================
('account.dashboard',             'en', 'Dashboard', 'account'),
('account.dashboard',             'ar', 'لوحة التحكم', 'account'),
('account.my_bookings',           'en', 'My Bookings', 'account'),
('account.my_bookings',           'ar', 'حجوزاتي', 'account'),
('account.welcome',               'en', 'Welcome, {name}!', 'account'),
('account.welcome',               'ar', 'مرحباً، {name}!', 'account'),
('account.profile_summary',       'en', 'Profile Summary', 'account'),
('account.profile_summary',       'ar', 'ملخص الملف الشخصي', 'account'),
('account.role_customer',         'en', 'Customer', 'account'),
('account.role_customer',         'ar', 'عميل', 'account'),
('account.role_super_admin',      'en', 'Administrator', 'account'),
('account.role_super_admin',      'ar', 'مدير النظام', 'account'),
('account.role_hotel_manager',    'en', 'Hotel Manager', 'account'),
('account.role_hotel_manager',    'ar', 'مدير فندق', 'account'),
('account.active',                'en', 'Active', 'account'),
('account.active',                'ar', 'نشط', 'account'),
('account.inactive',              'en', 'Inactive', 'account'),
('account.inactive',              'ar', 'غير نشط', 'account'),
('account.account_status',        'en', 'Account Status', 'account'),
('account.account_status',        'ar', 'حالة الحساب', 'account'),
('account.claim_booking',         'en', 'Claim Booking', 'account'),
('account.claim_booking',         'ar', 'استعادة حجز', 'account'),
('account.no_bookings',           'en', 'No bookings yet.', 'account'),
('account.no_bookings',           'ar', 'لا توجد حجوزات بعد.', 'account'),
('account.section_tours',         'en', 'Tours', 'account'),
('account.section_tours',         'ar', 'الجولات', 'account'),
('account.section_hotels',        'en', 'Hotels', 'account'),
('account.section_hotels',        'ar', 'الفنادق', 'account'),
('account.section_events',        'en', 'Events', 'account'),
('account.section_events',        'ar', 'الفعاليات', 'account'),
('account.section_transfers',     'en', 'Transfers', 'account'),
('account.section_transfers',     'ar', 'النقل', 'account'),
('account.booking_code',          'en', 'Booking Code', 'account'),
('account.booking_code',          'ar', 'رمز الحجز', 'account'),
('account.recent_bookings',       'en', 'Recent Bookings', 'account'),
('account.recent_bookings',       'ar', 'أحدث الحجوزات', 'account'),
('account.upcoming_bookings',     'en', 'Upcoming Bookings', 'account'),
('account.upcoming_bookings',     'ar', 'الحجوزات القادمة', 'account'),
('account.base_fare',             'en', 'Base Fare', 'account'),
('account.base_fare',             'ar', 'السعر الأساسي', 'account'),
('account.return_fee',            'en', 'Return Trip Fee', 'account'),
('account.return_fee',            'ar', 'رسوم رحلة العودة', 'account'),
('account.extras',                'en', 'Extras', 'account'),
('account.extras',                'ar', 'الإضافات', 'account'),
('account.discount',              'en', 'Discount', 'account'),
('account.discount',              'ar', 'الخصم', 'account'),
('account.flex_fee',              'en', 'Flexible Cancellation', 'account'),
('account.flex_fee',              'ar', 'إلغاء مرن', 'account'),
('account.room_fee',              'en', 'Private Room', 'account'),
('account.room_fee',              'ar', 'غرفة خاصة', 'account'),
('account.payment_status',        'en', 'Payment Status', 'account'),
('account.payment_status',        'ar', 'حالة الدفع', 'account'),
('account.invoice_number',        'en', 'Invoice Number', 'account'),
('account.invoice_number',        'ar', 'رقم الفاتورة', 'account'),
('account.timeline',              'en', 'Booking Timeline', 'account'),
('account.timeline',              'ar', 'الجدول الزمني للحجز', 'account'),
('account.payment_reference',     'en', 'Payment Reference', 'account'),
('account.payment_reference',     'ar', 'مرجع الدفع', 'account'),
('account.payment_method',        'en', 'Payment Method', 'account'),
('account.payment_method',        'ar', 'طريقة الدفع', 'account'),
('account.booking_reference',     'en', 'Booking Reference', 'account'),
('account.booking_reference',     'ar', 'مرجع الحجز', 'account'),
('account.service_name',          'en', 'Service', 'account'),
('account.service_name',          'ar', 'الخدمة', 'account'),
('account.customer',              'en', 'Customer', 'account'),
('account.customer',              'ar', 'العميل', 'account'),
('account.created_date',          'en', 'Created Date', 'account'),
('account.created_date',          'ar', 'تاريخ الإنشاء', 'account'),
('account.bookings_count',        'en', 'Total Bookings', 'account'),
('account.bookings_count',        'ar', 'إجمالي الحجوزات', 'account'),
('account.revenue',               'en', 'Revenue', 'account'),
('account.revenue',               'ar', 'الإيرادات', 'account'),
('account.cancelled_bookings',    'en', 'Cancelled Bookings', 'account'),
('account.cancelled_bookings',    'ar', 'الحجوزات الملغاة', 'account'),
('account.booking_summary',       'en', 'Booking Summary', 'account'),
('account.booking_summary',       'ar', 'ملخص الحجز', 'account'),
('account.issued_at',             'en', 'Issued', 'account'),
('account.issued_at',             'ar', 'صدر', 'account'),
('account.total_price',           'en', 'Total Price', 'account'),
('account.total_price',           'ar', 'السعر الإجمالي', 'account'),
('account.invoice_total',         'en', 'Invoice Total', 'account'),
('account.invoice_total',         'ar', 'إجمالي الفاتورة', 'account');
